version: 0.2

phases:
  install:
    commands:
      - apk add --no-cache py-pip
      - pip install docker-compose
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image ...
      - docker-compose build
  post_build:
    commands:
      - docker-compose push
