version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker-compose pull --ignore-pull-failures --parallel
  build:
    commands:
      - echo Building the Docker image ...
      - docker-compose build
  post_build:
    commands:
      - docker-compose push
