version: '3.3'

services:
  webapp:
    build:
      context: ./spring-boot-sample
      cache_from:
        - ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}/webapp:${IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}/webapp:${IMAGE_TAG}

  nginx:
    build:
      context: ./nginx
      cache_from:
        - ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}/nginx:${IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}/nginx:${IMAGE_TAG}