version: '3.3'

services:
  app:
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - .:/app
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
